### ISSUE TITLE
Mention about bs-platform 6.x requirement in README

### ISSUE THREAD

**Issue by thangngoc89** [zth/reason-relay#1]

**Comment by zth** [comment]
Hey!

There's actually a mention already in the README,
"Requires BuckleScript 6 (currently in beta), Relay == 5.0.0 and React >= 16.8.1"

...but I should probably make it much more prominent. Thanks!

**Comment by zth** [comment]
Resolved in 74dec89ef44b4582c728ac563b80538f34a2ad42.
