### ISSUE TITLE
Mutation results in compilation error in generated *_graphql.re file

### ISSUE THREAD

**Issue by Yakimych** [zth/reason-relay#100]
Hi! I've started converting a reason-apollo-hooks-based app to reason-relay and have encountered an issue after trying to implement a mutation. Seems like the generated types are circular for this case.

## Steps to reproduce:
1. Clone the "relay" branch from here: https://github.com/Yakimych/relogify/tree/relay
2. Run `npm run relay`. The files should get generated without errors.
3. Run `npm run build`.

The following error in `AddResultMutation_graphql.re` shows up:
`This type constructor's parameter, 'players_insert_input', can't be found. Is it a typo?`

The schema comes from Hasura and is public, so it should be possible to reproduce: https://hockeyapi.yakim.dev/v1beta1/relay.

**Comment by zth** [comment]
Ah right, it's an ordering issue. Thank you for reporting, I'll fix this soon.

**Comment by zth** [comment]
Fixed in https://github.com/zth/reason-relay/commit/ce39ada434fe9e73553bf41eaacf5fea7c3de5fb
