### ISSUE TITLE
Regression: certain enums get serialized as integers instead of strings

### ISSUE THREAD

**Issue by Yakimych** [zth/reason-relay#102]
I've noticed a regression after the latest release - mutation variables get serialized to integers in certain cases.

This is the relevant part of the mutation generated correctly (previous version of reason-relay):
```
community: {data: {name: "test"}, on_conflict: {constraint: "communities_name_key", update_columns: ["name"]}}
```

Now in version 0.11.0, I am getting the following (`communities_name_key` and `name` get serialized to **712960867** and **-922783157** respectively):
```
community: {data: {name: "test"}, on_conflict: {constraint: 712960867, update_columns: [-922783157]}}
```

I've quickly looked at the diff in generated types, and this part has indeed changed:

Working version (previous release):
```
communities_on_conflict = {
    [@bs.as "constraint"]
    constraint_: enum_communities_constraint,
    update_columns: array(enum_communities_update_column),

type enum_communities_constraint =
  pri [> | `communities_name_key | `communities_pkey];
```

Non-working version that serializes into integers (0.11.0):
```
communities_on_conflict = {
    [@bs.as "constraint"]
    constraint_: [
      | `communities_name_key
      | `communities_pkey
      | `FutureAddedValue(string)
    ],
```

Let me know if you would like a complete repro-scenario, I can get something up-and-running if necessary!

**Comment by zth** [comment]
Did you re-run the compiler after upgrading?

**Comment by zth** [comment]
Oh, and also, did you upgrade to `bs-platform` `8.2.0` specifically? Try those two things if you haven't already, otherwise I'll have to dig some.

**Comment by Yakimych** [comment]
Oh, sorry - looks like bs-platform is the culprit.

Unfortunately I cannot test this properly in my project though, since for some reason I get `File "bsconfig.json", line 4: Error: Unsupported jsx version 2` when I update, but I doubt this is somehow related to reason-relay. Tested quickly in a freshly created project and the mutation works as expected. Sorry again for the confusion, I should have read the release notes properly before opening the issue 🙂

**Comment by zth** [comment]
Haha no problem, glad it worked out!
