### ISSUE TITLE
[feature request] generate all reason types defined in schema.graphql for "client-side-only"-usage without a relay-server

### ISSUE THREAD

**Issue by farukg** [zth/reason-relay#103]
First of all: thx for this great library! :)

### Introduction
Right now, I'm trying to use relay in an application where the backend its talking to, doesn't even provide a graphql endpoint and the state is managed by redux. I don't count this as an excuse to not start using graphql & relay :D

### Goals
1. pretend there is a relay-server at the backend-side
2. treat the redux store as an additional data-source of the "relay-server"
3. use graphql-types as the "source-of-truth"-types wherever possible (we plan to generate also types for the backend)
4. having types generated from schema.graphql and ideally separated
   into clientOnly & server schema like described in [client-only-data-client-schema-extensions](https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#client-only-data-client-schema-extensions) in order to use them for not-yet-migrated components, maybe even importing from js-components
5. human-friendly type names, directly derived from graphql definitions, detached from relay-context (e.g. fragment, response, etc.)
6. helper functions for convenience (e.g. creating instances, component, resolvers, etc.)

### Motivation
In order to fully migrate to relay at some point in future, i want/have to start on the client and leverage the full power of relay & reason despite missing a server supporting graphql

### Current state
So far I managed to define a custom network layer with custom resolvers.

So now, I'm able to make request to the backend based on the query, get the current redux state or subscribe to the redux-store. I could even dispatch regular redux-actions in response to mutations. Thats already fantastic :D

For the resolvers I use my fork of [graphql-to-reason](https://github.com/farukg/graphql-to-reason ) which i modified so it generates records instead of Js.t to have nicer types. This introduced the limitation of having the same type for fields with the same name, otherwise they will prefixed. But I can live with that. The issue is that the generated types are, it feels like, already present in reason-relay. Also, they are slightly different, requiring unneccessary mappings, rely on my (probably buggy) fork and lack functions/constructors for client-usage since it was made for servers.

I also considered defining a query including every field to have the types generated. The issue here is that i would have to create the resolver types myself and the resulting type names include relay-context specific prefixes and namespaces resulting in very long names, especially for deeply nested queries. When using reason-relay with Query etc. thats not an issue having type-inference. But elsewhere it's a little ugly to work with :). In the library i mentioned above it is much nicer. It generates a module for each type in graphql. This is very convenient & remember-able as it is an almost 1-to-1 mapping from graphql.
You can have a look at this here: [basic.graphql](https://github.com/farukg/graphql-to-reason/blob/master/test/fixtures/basic.graphql) and generated reason types  [basic.re](https://github.com/farukg/graphql-to-reason/blob/master/test/output/basic.re)

### Note

I know implementing all of the goals i described is probably out-of-scope, but i wanted you to know the context.
I just hope its easy to strip out relay-naming-constrainst and generate nice reason types for the whole schema.

Please tell me what you think about what I'm trying to do and if you can think of other solutions.

**Comment by zth** [comment]
Hi! While a very interesting problem/project in itself, most of the things you talk about are indeed very much out of scope for this lib 😄 

I think your best bet is to just run your own instance of `graphql-js` on the client (maybe in a webworker to get it off the main thread if needed). 

Construct a schema, and expose that to Relay so Relay effectively queries that service. That service can then tie together data from various sources, whether it'd be from the Redux store, via external requests or what not. You'll have full control. 

I think that'll be your best bet going forward, even if it currently requires using JS/TS for that part as there are no Reason bindings for `graphql-js` AFAIK.

**Comment by farukg** [comment]
That part i have already done and it works fine :) 
It is just a custom network layer like so:
```reason
let network:
  (ReasonRelay.Network.operation, 'vars, ReasonRelay.cacheConfig) =>
  ReasonRelay.Observable.t(Js.Json.t) =
  (operation, variables, cacheConfig) => {
    let contextValue = {"operation": operation, "state": ReduxStore.getStore()};
    let gqlSource =
      graphql(. schema, operation.text, Resolvers.resolvers, contextValue, variables)
      |> Wonka.fromPromise;

    ReasonRelay.Observable.make(({next, error, complete, closed}) =>
      try({
        let sub =
          gqlSource
          |> Wonka.onPush((. x) => next(x))
          |> Wonka.onEnd((.) => complete())
          |> Wonka.publish;
        let subscription: ReasonRelay.Observable.subscription = {
          unsubscribe: sub.unsubscribe,
          closed,
        };
        Some(subscription);
      }) {
      | Js.Exn.Error(e) =>
        error(e);
        None;
      }
    );
  };
```

As you are already doing this when a query is defined, i wonder if it is possible to generate the graphql types for the whole schema which i want to use for the resolvers ?

**Comment by zth** [comment]
No, the compiler only takes care of operations defined to be used by Relay. I think what you're after is regular codegen (which you've already been using, as you've shown), which isn't something Relay deals with.

**Comment by farukg** [comment]
Oh ok, so you don't have the actual graphql types at hand somewhere, which could be easily written to a file, correct?

**Comment by zth** [comment]
Unfortunately no, I don't. The Relay compiler generates a structure _per GraphQL operation/fragment_ that's a combination of that GraphQL content and the schema. That's then transformed to Reason types. So there's unfortunately no place where the entire schema is converted to types.

But to be honest, I think rolling your own codegen is perhaps the easiest approach anyway as you'll likely have a few non-standard needs.

**Comment by farukg** [comment]
i understand, looks like i need to stick to my current sub-optimal solution :(
 
thx, for your quick response!
