### ISSUE TITLE
Docs: compilation errors in examples for subscriptions

### ISSUE THREAD

**Issue by Yakimych** [zth/reason-relay#104]
Hi! I've been trying to get subscriptions to work according to the docs, and have discovered several issues with the samples for RelayEnv.re here: https://reason-relay-documentation.zth.now.sh/docs/subscriptions#subscriptions-in-relay

1. The type annotation for `subscriptionFunction` indicates one input parameter, but the function itself takes 3:
```
let subscriptionFunction:
  ReasonRelay.Network.subscribeFn => ReasonRelay.Observable.t =
  (config, variables, _cacheConfig) => {
    let query = config.text;
...
```

2. `ReasonRelay.Observable.t` is asking for a type parameter (as defined in the Observable ReasonRelay module: `type t('response)`).

3. How is `SubscriptionTransportWS` defined? Are we binding `request`, `subscribe` and `unsubscribe` of the [SubscriptionClient defined here](https://github.com/apollographql/subscriptions-transport-ws/blob/e25d67ff9bcbdf9dc39cb8ddbbd0e75853252f1d/src/client.ts#L71)? Looks like e.g. `unsubscribe` is private in this case. Maybe it's easiest to just include the bindings that are used for the examples in the docs?

There might be more issues, but I haven't been able to get past those yet. Is there a working example somewhere that one can clone and try out in order to get going?

**Comment by zth** [comment]
This one is resolved in your PR https://github.com/zth/reason-relay/pull/106, right?

**Comment by Yakimych** [comment]
Yes, indeed! Closing this.
