### ISSUE TITLE
[RFC] Improving DX of Js.Nullable.t

### ISSUE THREAD

**Issue by zth** [zth/reason-relay#11]
As outlined in https://reason-relay-documentation.zth.now.sh/docs/quirks-of-reason-relay#nullability, we for various reasons need to model all nullable fields as `Js.Nullable.t`. This means that you'll end up switching a lot, and also doing `someValue |> Js.Nullable.toOption`, which isn't a great DX. I thought those interested could discuss possible improvments to the nullability situation here.

## Propsal: Vendor a modified version of `get_in` PPX.
https://github.com/jaredly/get_in_ppx `get_in` PPX is a PPX for dealing with the same issues as outlined here, but for pure `option` values. We could probably vendor and modify it into `get_nullable`, which might turn this situation:

```reason
let anotherNestedField = switch (data##someField |> Js.Nullable.toOption) {
| Some(someField) =>
  switch (someField##someNestedField |> Js.Nullable.toOption) {
  | Some(someNestedField) =>
    someNestedField##anotherNestedField |> Js.Nullable.toOption
  | None => None
  }
| None => None
};
```

...into something like this:

```reason
let anotherNestedField = [%get_nullable data##someField##?someNestedField##?anotherNestedField];
```

Thoughts and comments are much welcome.

**Comment by arnarthor** [comment]
I'm wondering if the approach that https://github.com/mhallin/graphql_ppx takes with `@bsDecoder` would work here. 

That way people could use `@bsDecoder(fn: "Js.Nullable.fromOption")` to instantly convert it to an optional instead.

I'm a bit skeptical on adding a separate PPX to deal with this since it can add a bit to the compile times.

**Comment by zth** [comment]
Solved in https://github.com/zth/reason-relay/commit/ae60b190d2804f2d87f798251f232a7818ce48ec , we now automatically convert nullables :tada:
