### ISSUE TITLE
Danger when querying interfaces

### ISSUE THREAD

**Issue by Arnarkari93** [zth/reason-relay#113]
I spotted a dangerous query that reason-relay generated types could prevent. I made a PR here https://github.com/sothebys/reason-relay/pull/1/files with the changes that result in the type system not giving errors but resulting in runtime errors.

Consider the following query
```
module Query = [%relay.query
  {|
    query TestNodeInterfaceQuery {
      node(id: "123") {
        __typename
        id
        ... on User {
          firstName
        }
        ... on Group {
          name
        }
      }
    }
|}
];
```

Then generating the types for this query reason-relay will not to create a variant type that you can switch over for `User` and `Group` instead a record will be generated with all properties marked as optional. This is because the field `id` id outside of the interface selections.
```
// ___generated___/TestNodeInterfaceQuery.re
type response = {
  id: String,
  firstName: option(String),
  name: option(String),
};
```

This can seem harmless at first but lets say if we add a fragment to get the user's lastname to the `User` like so:
```
module Query = [%relay.query
  {|
    query TestNodeInterfaceQuery {
      node(id: "123") {
        __typename
        id
        ... on User {
          firstName
          ... TestNodeInterface_user
        }
        ... on Group {
          name
        }
      }
    }
|}
];

  module Fragment = [%relay.fragment
    {|
    fragment TestNodeInterface_user on User {
      lastName
    }
  |}
  ];
```

We will get the property `fragmentRefs` as expected added to the `type response`, but If we try to pass the fragmentRefs to a component that uses the `lastName` property we will get runtime error if the query response is indeed a `Group` since `lastName` is not a valid proprty on the type `Group`.

Whould it make sense to generate the types so that variants are always generated?
So the same example as above would generate following types:
```
type response_user = {
  firstName: String
  fragmentRefs: [|` TestNodeInterface_user]
};
type response_group = {
  name: String
};
type response = {
  id: String
  _type: [ |`User(response_user) | `Group(response_group)]
};
```

**Comment by tsnobip** [comment]
wouldn't `fragmentRefs` be typed as optional here anyway?

**Comment by Arnarkari93** [comment]
At least right now. That is one solution. But would not generating a variant be the expected behaviour?

**Comment by tsnobip** [comment]
what I meant was that since `fragmentRefs` is optional, there should be no runtime error if it's not present, shouldn't it? I haven't checked myself, just wondering.

Regarding if it should be a variant, I guess it would indeed be more idiomatic, but it would require a runtime conversion, that might be unnecessary in the near future if rescript changes its representation of variants (still work in progress if I understood correctly).

**Comment by zth** [comment]
Hey @Arnarkari93 ! Sorry for missing this.

To make a long story short - you're absolutely right, the types are less than ideal for that particular use case. While I could theoretically fix it in the type generation of ReasonRelay, I've opted to stay as compliant as I can with the types that Relay generate, and this is actually a problem with the types generated by the compiler itself. 

It's a problem that I believe is being worked on in Relay, and there are a few related issues and PRs for improving that aspect of the type generation, like this one: https://github.com/facebook/relay/pull/3178

Meanwhile, as a work around, I believe you can force the selection to be a proper union by making no "base" selections on the interface itself, but rather duplicate all common selections on each interface member. While of course not at all ideal, I _believe_ that should work for now.

**Comment by Arnarkari93** [comment]
No worries, although it is not ideal the workaround is working for me just fine.

**Comment by zth** [comment]
Closing this, will most likely be resolved by the Relay Rust compiler.
