### ISSUE TITLE
questions: local state mgmt and rescript supports

### ISSUE THREAD

**Issue by nrako** [zth/reason-relay#114]
Hi! First, thank you very much for sharing this project! I've been exploring and playing with it and I love the promise!

Just two quick questions:

Is [Local State Mgmt](https://relay.dev/docs/en/local-state-management) supported? I see [commitLocalUpdate](https://github.com/zth/reason-relay/blob/0.11.0/packages/reason-relay/src/ReasonRelay.rei#L866) and [setLinkedRecords](https://github.com/zth/reason-relay/blob/0.11.0/packages/reason-relay/src/ReasonRelay.rei#L156) being exposed but no examples or tests and I do wonder if this can be done in a type safe way?

I know the new ReScript syntax `.res` is very bleeding edge but I do wonder if there's any intention to support it at any point in time? Any pointers towards what pre-required steps might be required to support ReScript?

**Comment by zth** [comment]
Hey @nrako!

Local state management is supported via `commitLocalUpdate` as of now. You're indeed right that's the wild west though, with no type safety. I've been eyeing binding [commitPayload](https://relay.dev/docs/en/a-guided-tour-of-relay#commitpayload) instead, which is a type safe way of interacting with the store (allowing you to commit queries locally in a type safe way). When I last looked at this my idea was the following:

For each query that is annotated with `@raw_response_type`, autogenerate a function called `commitLocalPayload` like: `Query.commitLocalPayload(variables, response)`. That'd give us a type safe API for local updates, that's actually fairly OK to use (as compared to replicating it all with local updates), and safe in the sense that you can't use it unless you also annotate the query with `@raw_response_type`, which would ensure you're committing the right thing.

I'll hopefully get around to that eventually, and I'd be happy to guide anyone interested in contributing through exactly how that could be implemented. I personally don't have free time to do it as of now though.

As for ReScript syntax, adding support for parsing ReScript syntax (as in you can write your GraphQL in `.res` files) is hopefully pretty easy. I'm hoping it's really only about making [this file](https://github.com/zth/reason-relay/blob/master/packages/reason-relay/language-plugin/src/FindGraphQLTags.ts) understand ReScript's syntax for extension points (I believe what is `[%relay.query {| ... |}]` in Reason syntax is ```@relay.query(` ... `)``` in ReScript). So, hopefully a really easy thing. 

I won't be using the new ReScript syntax myself for the foreseeable future though, so contributions are much appreciated.

Thanks for your interest!

**Comment by nrako** [comment]
Hey @zth!

I very much appreciate for your time and these precisions, thanks!

The `commitPayload` & `@raw_response_type` combo seems to be a great approach! I'm still very green in regard to Relay and I just learned something new, but I'll try to investigate in my spare time. In due time, I might take you on your offer for some guidance. Of course, if I manage to get something up and running I'll be happy to contribute.

Regarding ReScript syntax, that's encouraging, I didn't knew where to start. With this pointer I'm now keen to give it a try! Hopeful I can get some result and again I'll be sure to followup if I get anywhere.

> I won't be using the new ReScript syntax myself for the foreseeable future though

Are you planning to stick to ReasonML? Your comment actually makes me curious. I'm not involved but from what I followed on Discord and the forum I thought the community was mostly supportive of the new ReScript syntax.

Thanks you again for taking the time to answer. I'm closing this issue and will try to followup soon when my free time allows it.

Cheers!

**Comment by nrako** [comment]
So I was eager to gives this a good try but I immediately hit issues and very quickly [felt out of my depth](https://twitter.com/davesnx/status/1317176154869108738).


Here's the deal when I tried to build `reason-relay-ppx` I hit that "notorious" [macOS `-Wno-implicit-function-declaration`](https://github.com/ocaml/opam-repository/pull/17379) issue:
```
    ...
    Fatal error: exception Invalid_argument("Sys.getcwd not implemented")
    make[1]: *** [camlinternalFormatBasics.cmi] Error 2
    make: *** [coldstart] Error 2
    error: command failed: './esy-build' (exited with 2)
    esy-build-package: exiting with errors above...

  building ocaml@4.6.1000
esy: exiting due to errors above
```

Then I naively thought that I could try to upgrade the ocaml version since it doesn't seem that [esy](https://github.com/esy/esy/issues/1177) have made the required patches – new ocaml npm packages releases or whatever is needed.

But then of course when I tried to build `reason-relay` I get:
```
...
[10/168] Building __tests__/Test_unions.reast
FAILED: __tests__/Test_unions.reast
/Users/nrako/src/nrako/reason-relay/packages/reason-relay/node_modules/bs-platform/darwin/bsc.exe  -warn-error +101 -bs-jsx 3 -ppx /Users/nrako/src/nrako/reason-relay/packages/reason-relay/./reason-relay-ppx/_esy/default/build/default/bin/ReasonRelayPpxApp.exe  -o __tests__/Test_unions.reast -bs-syntax-only -bs-binary-ast /Users/nrako/src/nrako/reason-relay/packages/reason-relay/__tests__/Test_unions.re
Fatal error: exception (Failure "Ast_mapper: OCaml version mismatch or malformed input")
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "src/migrate_parsetree_driver.ml", line 557, characters 4-122
Re-raised at file "parsing/location.ml", line 904, characters 14-25
Called from file "src/migrate_parsetree_driver.ml", line 565, characters 6-56
Called from file "bin/ReasonRelayPpxApp.re", line 4, characters 0-28

  We've found a bug for you!
  /Users/nrako/src/nrako/reason-relay/packages/reason-relay/__tests__/Test_unions.re

  Error while running external preprocessor
Command line: /Users/nrako/src/nrako/reason-relay/packages/reason-relay/./reason-relay-ppx/_esy/default/build/default/bin/ReasonRelayPpxApp.exe '/var/folders/r_/zrvs586j3zn81kw4md3g0ndm0000gn/T/ppxbf951eTest_unions.re' '/var/folders/r_/zrvs586j3zn81kw4md3g0ndm0000gn/T/ppx4ffd30Test_unions.re'
```

Of course because buckelscript uses Ocaml: 4.06.1:

```
❯ bsc -v
BuckleScript 8.2.0 ( Using OCaml:4.06.1+BS )
```

I'm stuck and I'm not sure what I'm supposed to do now? I was looking forward to try #115 and maybe contribute to it with some tests.

Any help or direction would be greatly appreciated.

**Comment by sorenhoyer** [comment]
You don't need to build the ppx files - just run the ci-build.sh (ish... don't remember the exact name) script to generate the _release folder and copy the ppx files from node_modules/reason-relay (from an existing install of the latest published version) and pack it as tgz and install.

I can share my boilerplate next time I'm at the pc which is on monday - there i have packed a build in a local .tgz file with rescript support from the open PR.

**Comment by nrako** [comment]
Thanks @sorenhoyer – using `./build-ci.sh` and copying the ppx files worked.

However, at this point I'm just facing different issue; again probably all due my ignorance in this bleeding edge environment. I'm not totally discouraged but at this point I think I'd love to see your boilerplate before doing any more experimentation. Especially if your boilerplate contains some query, mutation and fragment examples.

For reference this is what I'm facing now:
```
[RE] ERROR:
[RE] Parse error: Syntax Error: Expected "$", found <EOF>.
[RE]
[RE] /path/file.res:3:61
[RE] 2 |
[RE] 3 |   query Space_Query($org_slug: String!, $space_slug: String!
[RE]   |                                                             ^ in "path/file.res"
Watching for changes to re/res...
[RE] Watching for changes to graphql...
```

```reason
module SpaceOrg = %relay.query(
  `
  query Space_Query($org_slug: String!, $space_slug: String!) {
    spaces_connection(where: {org: {slug: {_eq: $org_slug}}, slug: {_eq: $space_slug}}) {
      edges {
```

**Comment by zth** [comment]
That looks like the regex isn't quite working as expected, right @sorenhoyer ? 

Regexes really aren't great for parsing code, but unfortunately it's what we're using right now 😞 Sorry for making you go down that rabbit hole..

@nrako I don't think anything is wrong at your end though, so don't despair.

@sorenhoyer what do you think of adding a few tests to the file doing the parsing/looking for tags in your PR? That'd allow us to cover corner cases like this with more confidence.

**Comment by sorenhoyer** [comment]
@nrako I pushed a very early version of the new boilerplate I'm working on. The idea is that in time it will cover preloaded + nested queries, (refetchable) fragments, pagination/lazyloading, mutations, subscriptions live queries etc. But at least this is a start.

I will look into the regex again, to see if I can find the culprit. Can you paste your entire file?

@zth Sure - I'll add a few tests. Good idea.

**Comment by nrako** [comment]
@sorenhoyer – I can look into sharing a minimal example later today (in 8-10 hours), but I really had that issue to any query with variables.

**Comment by nrako** [comment]
Sorry I couldn't followup as I planned but I'm positive that any query with variables like in my example https://github.com/zth/reason-relay/issues/114#issuecomment-711285829 would fail, and if I removed all the `($variables: ...)` then it works.

**Comment by sorenhoyer** [comment]
@nrako no worries, I'll make sure to get it to work with variables and write some tests for it. Unfortunately this is a quite busy week for me, but I'll try to get it done during the week. Should be very simple to fix. Thanks for the feedback :p

**Comment by zth** [comment]
Hey @nrako just an FYI, I ended up implementing the thing I was originally talking about in this thread - `commitLocalPayload` for queries, for local state management. Check out the PR here: https://github.com/zth/reason-relay/pull/118
