### ISSUE TITLE
Support for @inline fragments

### ISSUE THREAD

**Issue by Arnarkari93** [zth/reason-relay#116]
How would reason-relay tackle supporting inline fragments? So non-react function can take advantage of data masking and getting correct reason types?

I tried binding it myself but was not successful since I could not find out how to get the module type that `[%relay.fragment]`

**Comment by zth** [comment]
`@inline` should work as-is now already, is it not? Or are you referring to `readInlineData`, which would allow you to read a fragment via a fragment ref outside of render/not via a hook?

**Comment by Arnarkari93** [comment]
Yes, I am referring to readInlineData.

**Comment by zth** [comment]
Let me try and bind it real quick and get back to you... 😄

**Comment by Arnarkari93** [comment]
This is as far as I got.
```
module type OperationType = {
   type fragment;
}

module type Operation = {
  type fragmentRef; 
  type operationType; 
  let node: ReasonRelay.fragmentNode;
  module Types: OperationType;
};

module ReadInlineData = (Operation: Operation) => {
  [@bs.module "react-relay"]
  external readInlineData:
    (ReasonRelay.fragmentNode, Operation.fragmentRef) => Operation.Types.fragment =
    "readInlineData";

  let read = (fragmentRef) => readInlineData(Operation.node, fragmentRef);
};
```

But I cant get type type `ReasonRelay.fragmentRefs(|> Some fragment )`

**Comment by zth** [comment]
I think what we should do isn't binding it in general, but rather generate code for it via the generated fragment module only when the fragment has `@inline` defined. So the API for using it would be roughly:
```
module Fragment =  [%relay.fragment {|
  fragment SomeUser_user on User @inline {
    ...
  }
|}];

let logData = user  => {
  SomeLoggingModule.log(Fragment.readInline(user));
);
``` 

Are you following how I'm thinking? I'll give it a try now and see if I can get it together real quick.

**Comment by Arnarkari93** [comment]
Yes, I follow, so we need to add it in the ppx, that's where you lose me 😬

**Comment by Arnarkari93** [comment]
I am not that comfortable adding it to ppx but I am willing to try.

**Comment by zth** [comment]
Give me a few minutes here and I'll have something you can review and hopefully get some insight on my thinking around adding stuff to the PPX, and then I can guide you through doing it yourself for the next feature we want to bind that touches the PPX, if you're interested?

**Comment by Arnarkari93** [comment]
yes! very interested.

**Comment by zth** [comment]
Check this out: https://github.com/zth/reason-relay/compare/bind-read-inline

Is that making sense?

I haven't actually tested it yet so it might not work 😅

**Comment by zth** [comment]
...I'm making a few changes to that, bear with me a few more minutes.

**Comment by Arnarkari93** [comment]
This looks good to me! Thank you for responding so quickly! I will try it out locally when I get a change.

**Comment by zth** [comment]
Implemented in https://github.com/zth/reason-relay/pull/117
