### ISSUE TITLE
Query.fetch should return ReasonRelay.Observable.t('a) 

### ISSUE THREAD

**Issue by leoancap** [zth/reason-relay#138]
Since fetchPromised was removed, there is no way for the user to have access to the actual observable. So, instead of returning unit when calling Query.fetch, do return the actual observable. 

`let promise = Query.fetch(~variables=(), ~environment, ())->ReasonRelay.Observable.toPromise
`

**Comment by zth** [comment]
Thank you, will fix for the next version!

**Comment by zth** [comment]
Closed in https://github.com/zth/reason-relay/commit/1934bf4fb6d097124dfd82106d9c7917cd337a93

The best solution ended up being adding back a version of `Query.fetchPromised`.
