### ISSUE TITLE
Is it possible to adopt rescript/reason-relay incrementally?

### ISSUE THREAD

**Issue by webican** [zth/reason-relay#143]
Hi,

I have a fairly large codebase with 209 Relay fragments written in TypeScript that I'd like to switch to Rescript. I'd like to know if it would be feasible to migrate incrementally just 1 component with (usually) 1 fragment at a time?

I'm already running latest experimental React + experimental Relay in concurrent mode without problems using nothing but functional components and hooks. I'm also using IsomorphicRouter with a custom plugin to load graphql queries and pass data down the component tree.

**Comment by zth** [comment]
Hi @webican ! It's easy to re-use the environment between TS/ReScript (so the cache etc is shared), but there's no way out of the box to use both ReScript and TS at the same time (meaning including fragments defined in TS in ReScript, and vice versa).

This is however a use case that I'm interested in supporting, and I have a few ideas for how it possibly could be supported. So if you're interested and willing to experiment some, we could throw some ideas around for the easiest way to support this?

**Comment by webican** [comment]
Hi @zth Of course I'm interested in experimenting, though I don't think I would be of much help considering I haven't written a single line of ReScript code yet.

Another thing probably worth mentioning is that I'm using @babel/preset-typescript for transpiling TS and babel-plugin-relay for runtime graphql artifacts with Webpack.

**Comment by zth** [comment]
@webican I'm hoping there won't be too much ReScript involved at all at this point. Let's continue discussing this on our Discord: https://discord.gg/wzj4EN8XDc

**Comment by zth** [comment]
Short answer - yes, it's possible, and @webican graciously started documenting it here: https://github.com/zth/reason-relay/pull/157
