### ISSUE TITLE
Watchman deleting generated .js files because they are not marked with @generated

### ISSUE THREAD

**Issue by bdj** [zth/reason-relay#146]
When running ReasonRelay in watch mode, the .js files sporadically disappear because watchman thinks they are not generated files. I think a solution could be to preserve the comment from the .re file as mentioned here: https://github.com/rescript-lang/rescript-compiler/issues/662

**Comment by zth** [comment]
Good catch! It at least won't hurt to put it in there, so I'll make sure to add it to the next release.

**Comment by zth** [comment]
Fixed in https://github.com/zth/reason-relay/commit/518de066f5912e30f31233a594fb142cfacee696
