### ISSUE TITLE
Docs Demo

### ISSUE THREAD

**Issue by idkjs** [zth/reason-relay#16]
Is the code from the Docs example in a repo somewhere that can be referenced?

I am referring to code like that found here: https://reason-relay-documentation.zth.now.sh/docs/making-queries#making-queries

```ocaml
/* UserProfile.re */
module Query = [%relay.query {|
  query UserProfileQuery($userId: ID!) {
    userById(id: $userId) {
      firstName
      lastName
    }
  }
|}];
```

Thank you.

**Comment by zth** [comment]
Hey! No, unfortunately not. Most of the code in the docs is to illustrate specific points, but there's similar code for each concept in the example repo if that helps?
