### ISSUE TITLE
Use open poly variant to cover the FUTURE case

### ISSUE THREAD

**Issue by rickyvetter** [zth/reason-relay#19]
Right now the SchemaAsset generated file uses a marker to signify that additional values could be added to the schema later so it is unsafe to exhaustively match. Could we instead use an open poly variant like so:

```
type t('a) = [> | `Case1 | `Case2 ] as 'a;`
```

**Comment by rickyvetter** [comment]
Yeah - exactly. I am hoping that with the poly variant + some PR like https://github.com/BuckleScript/bucklescript/pull/3801 but for poly variant would allow for a 0 runtime version of SchemaAsset. This would mean you'd have the very large Reason file, but JS byte size would be unaffected.

**Comment by zth** [comment]
@rickyvetter I'm intrigued! And I agree that would be the best thing to do. However, I'd like to wait until that actually lands in BuckleScript before I change anything. Do you have any insight on ongoing work for that particular feature? 

At that point `SchemaAssets.re` could also be removed (although I plan on putting a few other things in there, so it might not after all), which would be nice.

**Comment by zth** [comment]
@rickyvetter likely starting work on this soon given that BS is approaching shipping that feature from what I can see. `SchemaAssets.re` is gone too now, for other reasons as well.

**Comment by zth** [comment]
This is implemented here https://github.com/zth/reason-relay/pull/90 although in a slightly different shape. Waiting a stable BS release with the feature, and it'll be merged after that.

**Comment by zth** [comment]
Fixed in https://github.com/zth/reason-relay/commit/e36948f5b1d800c8a17d10e92e207308bb299aa8 🎉
