### ISSUE TITLE
Document local development

### ISSUE THREAD

**Issue by Arnarkari93** [zth/reason-relay#33]
It would be really nice to have a section in the readme that documents local development.

**Comment by zth** [comment]
Yes, that's a great idea! It's not terribly straight forward now, right ;) I'm putting this on my todo and will try and get it done as soon as I can.

**Comment by Arnarkari93** [comment]
Thank you! 🎉

**Comment by zth** [comment]
@Arnarkari93 I started doing this in https://github.com/zth/reason-relay/blob/master/LOCAL_DEVELOPMENT.md <- could you check that out and let me know what you're missing?

**Comment by Arnarkari93** [comment]
Good job, I think this documentation answers everything I was looking for. I was many confused about how the PPX was built for release. Thanks again.

**Comment by zth** [comment]
Great! Ideally that'll be done in a much better way with GitHub Action or similar soon. But until then, you know! ;)
