### ISSUE TITLE
React / Relay version update (experimental)

### ISSUE THREAD

**Issue by sync** [zth/reason-relay#49]
I just updated my project to and everything seems to work fine, just wanted to let you know and feel free to delete this issue:

```
"react": "0.0.0-experimental-e5d06e34b",
 "react-dom": "0.0.0-experimental-e5d06e34b",
 "react-relay": "0.0.0-experimental-895a6fe0",
```
and relay 9.1.0 

```
"relay-runtime": "9.1.0",
"babel-plugin-relay": "9.1.0",
"relay-compiler": "9.1.0",
"relay-config": "9.1.0",
```

**Comment by zth** [comment]
Ah, great! I'll look at upgrading and cutting a new release as soon as I get a change 👍 Thanks!
