### ISSUE TITLE
Fragment with top-level union type.

### ISSUE THREAD

**Issue by Arnarkari93** [zth/reason-relay#50]
I get an error when trying to define a fragment as a top-level node in a fragment. Let's say I have a `school` query and then I define in a fragment for the different `classes`

```
// school query
school {
  id
  name
  classes {
    __typename
    ... Classes_fragment
  }
}


// class fragment
fragment Classes_fragment on Classes {
  __typename
  ... on Math {
    room
    hasExam
  }
  ... on English {
    teacherName
  }
}
```

This should be a valid query/fragment set up in Relay if I am not mistaken. However, I get the error: 

```
ERROR:
Error writing modules:
TypesTransformer.No_extractable_operations_found,19
```

It looks like it has something todo with defining both `__typename` in the `query` and the `fragment`. ReasonRelay enforces to define a `__typename` in the `query`. If I remove the `__typename` from the `fragment` like so: 

```
// class fragment
fragment Classes_fragment on Classes {
  ... on Math {
    room
    hasExam
  }
  ... on English {
    teacherName
  }
}
```

then `relay-compiler` does compile with out errors but it does not generate variants for the fragment types as I suspected. It will instead define type like:

```
// actual 
type fragment = {
   room: string,
   hasExam: bool,
   teacherName: string
   ...
}

// exptected
type fragment_math = {
  room: string,
  hasExam: bool
};
type fragment_english = {
  teacherName: string
};
type fragment = [
  | `Math(fragment_math)
  | `English(fragment_english)
  | `UnselectedUnitonMember(string)
]
```

Is my setup wrong in some way or is this a real issue?

**Comment by zth** [comment]
Hey @Arnarkari93 , thank you for reporting this!

I wonder, any chance you could test whether this works in a regular JS Relay project, and if so, how the generated types look? 

Here's an example repo you can use: https://github.com/relayjs/relay-examples/tree/master/issue-tracker

It uses the GitHub API so there should be unions available to test on.

Thanks!

**Comment by Arnarkari93** [comment]
Hi @zth thank you for the answer. I added a PR to my fork of the issue-tracker and added a case for this. Seems like the types are being generated correctly in JS
https://github.com/Arnarkari93/relay-examples/pull/1

**Comment by zth** [comment]
Thank you! So this happens because I haven't accounted for fragments potentially being unions in ReasonRelay. 

I think I have a pretty good understanding of what's going on and how it potentially can be fixed, but it's a problem that touches a lot of the code base, and I don't really know when I'll have time to have a proper look at this. 

Is this something you'd be interested in taking a stab at fixing if I guide you through the process?

**Comment by Arnarkari93** [comment]
Yes, I will be glad to contribute. It would be good to get some guidance to get started.

**Comment by zth** [comment]
Excellent! Let me get back to you here with a thorough explanation of where to start. I'll make it as elaborate as I can, hopefully it'll serve as some form of development documentation 😄
