### ISSUE TITLE
Error on older Mac Os X versions

### ISSUE THREAD

**Issue by ppsreejith** [zth/reason-relay#61]
First of all, thanks for the awesome work you're doing :) 

On older OSX versions (10.13.6), when proceeding after installing this module, it throws an error:
`dyld: Symbol not found: ____chkstk_darwin`
and additional error
`Referenced from: /path/to/my-project/node_modules/reason-relay/ppx (which was built for Mac OS X 10.15)`

I'm running OSX version 10.13.6

I fixed it by compiling the ppx from source after cloning the project and replacing the installed ppx.
`cd packages/reason-relay/reason-relay-ppx/`
`esy build`
`cp _esy/default/build/default/bin/ReasonRelayPpxApp.exe ../../../path/to/my-project/node_modules/reason-relay/ppx`

Hopefully, this will help someone else too 👍

**Comment by zth** [comment]
@ppsreejith Hey! Thanks for reporting that, I actually had no clue that differed between versions 😅 I'll leave this open for a while, should probably add some note to the README or investigate if I can get rid of that error all together and build for all versions at once.

**Comment by zth** [comment]
Closing this now, but thanks for noticing, and hopefully other people with the same issue can find this issue still even if it's closed.
