### ISSUE TITLE
Update on Hasura Relay Compatibility

### ISSUE THREAD

**Issue by ppsreejith** [zth/reason-relay#84]
The docs on [Using with Hasura](https://reason-relay-documentation.zth.now.sh/docs/using-with-hasura) mention that:

> As of now, Hasura does not provide the primitives needed in the schema for Relay to fully work with it.

As of v1.3.0-beta.1, Hasura is relay compliant.
Source: The [issue page](https://github.com/hasura/graphql-engine/issues/721)

I've tested this on my own machine. I'm planning to use reason-relay with Hasura. If it helps, I can add some docs on how to set up Hasura with Reason-Relay.

Just informing here. Feel free to delete this issue :)

**Comment by zth** [comment]
Thanks! Adding some information on using ReasonRelay with Hasura would be great if you're up for it! 🙂
