### ISSUE TITLE
refetch should return a Disposable

### ISSUE THREAD

**Issue by tsnobip** [zth/reason-relay#93]
according to the Flow types `refetch` functions should return a `Disposable.t` instead of unit:
https://github.com/facebook/relay/blob/c5153f7c348fcc8b8ea195474eb35538b6a1870f/packages/relay-experimental/useRefetchableFragmentNode.js#L101
that would help to stop the side effects on cleanup.

**Comment by zth** [comment]
Fixed in https://github.com/zth/reason-relay/commit/a7dc516ad524dfecc1b5c5f6403d6b543ca0a695.
