### ISSUE TITLE
fragmentRef of a conditionally included fragment can be null

### ISSUE THREAD

**Issue by tsnobip** [zth/reason-relay#94]
today fragmentRefs are not typed as optional, but they can be null when when they reference a fragment that is conditionally included with  `@include` and when the condition is false.

**Comment by zth** [comment]
I'm going to go ahead and close this for now, but yes, this is sadly expected and I believe it's a limitation in Relay itself. It's quite annoying so I'll make sure to try and figure out a solution, but right now it's expected.
